import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ThemeToggleButton from "./toggele";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MY Blog",
  description: "Generated by PG",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans bg-white dark:bg-gray-900">
        <ThemeToggleButton />
        <Navbar />
        <main className="px-4 md::px-6 prose prose-xl prose-slate dark:prose-invert mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
