import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ThemeToggleButton from "./toggele";
import MyProfilepic from "./components/MyProfilepic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MY Blog",
  description: "Generated by PG",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-sans bg-white dark:bg-gray-900'>
      <ThemeToggleButton/>
        <Navbar/>
        <MyProfilepic/>
        {children}
        </body>
    </html>
  );
}
